<a href="https://colab.research.google.com/github/Yashcode007/pytorch/blob/main/pytorch_nn_hand_on.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print("GPU Available:", torch.cuda.is_available())

2.6.0+cu124
GPU Available: True


In [ ]:
import torch
import torch.nn.functional as F

x = torch.tensor([2.0,3.0])

# Manually setting weights and bias
w = torch.tensor([0.5,-1.0])
b = torch.tensor(2.0)

z = torch.dot(x,w) + b

In [ ]:
print("Weighted Sum(z):", z.item())

output = F.relu(z)
print("Activated output(ReLU)", output.item())

output_tanh = torch.tanh(z)
print("Activated output(Tanh):", output_tanh.item())

output_sigmoid = F.sigmoid(z)
print("Activated output(Sigmoid:", output_sigmoid.item())

Weighted Sum(z): 0.0
Activated output(ReLU) 0.0
Activated output(Tanh): 0.0
Activated output(Sigmoid: 0.5


Building a 2 Layer Neurat Network on Dummy Data

| Input (x₁, x₂) | Label (y) |
| -------------- | --------- |
| \[0, 0]        | 0         |
| \[0, 1]        | 1         |
| \[1, 0]        | 1         |
| \[1, 1]        | 0         |


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
y = torch.tensor([[0.], [1.],[1.], [0.]])   # target labels

In [ ]:
b = nn.Linear(2,4)

In [ ]:
b

Linear(in_features=2, out_features=4, bias=True)

In [ ]:
class SimpleNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(2,4)   #input layer(2 -> 4 neurons)
    self.fc2 = nn.Linear(4,1)   #output layer (4->1)

  def forward(self,x):
    x = torch.relu(self.fc1(x))   # hidden layer + Relu
    x = torch.sigmoid(self.fc2(x))  # output layer + sigmoid(binary)
    return x


model = SimpleNet()

In [ ]:
criterion = nn.BCELoss()      # Binary Cross Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.1)

for epoch in range(1000):
  y_pred = model(X)
  loss = criterion(y_pred,y)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch%100 == 0:
    print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.7097
Epoch 100, Loss: 0.6940
Epoch 200, Loss: 0.6938
Epoch 300, Loss: 0.6936
Epoch 400, Loss: 0.6935
Epoch 500, Loss: 0.6934
Epoch 600, Loss: 0.6934
Epoch 700, Loss: 0.6933
Epoch 800, Loss: 0.6933
Epoch 900, Loss: 0.6933


In [ ]:
print("Predictions after training:")
with torch.no_grad():
  preds = model(X)
  print(torch.round(preds))

Predictions after training:
tensor([[0.],
        [0.],
        [1.],
        [1.]])


| Function           | Purpose                                   |
| ------------------ | ----------------------------------------- |
| `BCELoss()`        | Compares predicted vs. true binary labels |
| `SGD`              | Optimizer that updates weights/bias       |
| `zero_grad()`      | Clears old gradients                      |
| `loss.backward()`  | Calculates new gradients via backprop     |
| `optimizer.step()` | Applies those gradients to update weights |


Visulaisation of the weight updates in training loop

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

class SimpleNet(nn.Module):
  def __init__(self) :
    super().__init__()
    self.fc1 = nn.Linear(2,4)
    self.fc2 = nn.Linear(4,1)

  def forward(self,x):
    x = torch.relu(self.fc1(x))
    x = torch.sigmoid(self.fc2(x))
    return x

In [ ]:
model = SimpleNet()

criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.1)

for epoch in range(1000):
  y_pred = model(X)
  loss = criterion(y_pred,y)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 100 == 0:
        print(f"Epoch {epoch} | Loss: {loss.item():.4f}")
        print("fc1 weights:")
        print(model.fc1.weight.data)
        print("fc1 bias:")
        print(model.fc1.bias.data)
        print("-" * 30)

Epoch 0 | Loss: 0.7063
fc1 weights:
tensor([[ 0.1131, -0.0943],
        [-0.0959, -0.2817],
        [ 0.1919, -0.6261],
        [ 0.4324, -0.4234]])
fc1 bias:
tensor([-0.0341, -0.0271, -0.4396, -0.3556])
------------------------------
Epoch 100 | Loss: 0.6360
fc1 weights:
tensor([[ 0.3523, -0.3583],
        [-0.0959, -0.2817],
        [ 0.1919, -0.6261],
        [ 0.6739, -0.5606]])
fc1 bias:
tensor([-0.0059, -0.0271, -0.4396, -0.1141])
------------------------------
Epoch 200 | Loss: 0.5538
fc1 weights:
tensor([[ 0.6266, -0.6362],
        [-0.0959, -0.2817],
        [ 0.1919, -0.6261],
        [ 0.9216, -0.9273]])
fc1 bias:
tensor([-0.0088, -0.0271, -0.4396, -0.0099])
------------------------------
Epoch 300 | Loss: 0.5088
fc1 weights:
tensor([[ 0.8186, -0.8311],
        [-0.0959, -0.2817],
        [ 0.1919, -0.6261],
        [ 1.1577, -1.1665]])
fc1 bias:
tensor([-0.0114, -0.0271, -0.4396, -0.0130])
------------------------------
Epoch 400 | Loss: 0.4928
fc1 weights:
tensor([[ 0.9291

Learning Rate (lr) controls how big a step the optimizer takes during weight updates

If the lr is too high:-
- We may overshoot the minimum
- Loss might bounce wildly

If the lr is too low:-
- Model trains very slowly
- Might get stuck in local minima